name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: cp config/database.yml.sample config/database.yml
      - run: cp docker-compose.yml.sample docker-compose.yml
      - run: sed -i "s/BUNDLE_PATH=.*$/BUNDLE_PATH=\/app\/vendor\/bundle/g" docker-compose.yml
      - run: docker-compose build && docker-compose pull
      - run: docker-compose run --rm web bundle install
      - run: docker-compose run --rm web bundle exec rake db:create
      - run: docker-compose run -e RAILS_ENV=test --rm web bundle exec rake db:migrate
      - name: build
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        run: docker-compose run --rm web bundle exec rspec && docker-compose run -e CODECLIMATE_REPO_TOKEN --rm web bundle exec codeclimate-test-reporter
